services:
  - type: web
    name: cbc-api
    env: python
    plan: free
    buildCommand: |
      ./build.sh
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production